---
title: "R Markdown Presentation & Plotly"
author: "Oscar Alonso"
date: "`r Sys.Date()`"
output:
  slidy_presentation: default
  beamer_presentation: default
  ioslides_presentation: default
subtitle: "Week_3: Peer-graded Assignment"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Prepare data and libraries

```{r message=FALSE, warning=FALSE}
# Librerias
library(dplyr)
library(ggplot2)
library(plotly)
library(readr)
```

```{r message=FALSE, warning=FALSE}
# Cargar Datos
penguins <- read_csv("penguins.csv")
```

## PENGUIN CLASSIFICATION DATA I
#### *Clean data and structure it*

```{r message=FALSE, warning=FALSE, comment="", fig.align='center'}
# Limpiar datos
penguins <- penguins %>%
  na.omit()
# Resumen de datos
summary(penguins)
```
## PENGUIN CLASSIFICATION DATA II
```{r message=FALSE, warning=FALSE, comment="", fig.align='center'}
penguins$species <- as.factor(penguins$species)
penguins$island <- as.factor(penguins$island)
penguins$sex <- as.factor(penguins$sex)
str(penguins)
```
## PENGUIN WEIGHT BY ISLAND AND SPECIES
```{r fig.height=6.5, fig.width=14, message=FALSE, warning=FALSE, comment="", fig.align='center'}
# Graficar
plot_ly(penguins, x = ~island, y= ~body_mass_g, type = "box", color = ~factor(species)) %>% 
  layout(boxmode = "group") %>% 
  layout(title = "PENGUINS", xaxis = list(title = 'Island'), 
         yaxis = list(title = 'Body mass in g'), legend = list(title=list(text='Species of penguin')))
```





